<?php

namespace CMSilex\Forms\Types;

use CMSilex\Entities\Category;
use CMSilex\Entities\Post;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub

        $builder->add('categories', EntityType::class, [
            'class' => Category::class,
            'multiple' => true,
            'expanded' => true,
            'allow_extra_fields' => true,
        ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Post::class
        ]);
    }

    public function getParent()
    {
        return PageType::class;
    }
}